#!/bin/bash

set -e

# configuration
FAN_MODE="advanced"
FAN_VALUES=("60:0" "70:25" "80:50" "85:75" "90:100" "95:125" "100:150")

SHIFT_MODE="comfort"
BATTERY_MODE="medium"

# helpers
SYS_DIR="/sys/devices/platform/msi-ec"
CPU_DIR="$SYS_DIR/cpu"

FAN_MODE_FILE="$SYS_DIR/fan_mode"
SHIFT_MODE_FILE="$SYS_DIR/shift_mode"
BATTERY_MODE_FILE="$SYS_DIR/battery_mode"

i=0
for tuple in "${FAN_VALUES[@]}"; do 
    IFS=':' read temp speed <<< "$tuple"

    echo "set fan speed to $speed% for $temp°C"

    echo "$i=$temp" > "$CPU_DIR/table_temp"
    echo "$i=$speed" > "$CPU_DIR/table_fan_speed"

    i=$((i+1))
done

echo "Set fan mode: $FAN_MODE"
echo "$FAN_MODE" > "$FAN_MODE_FILE"

echo "Set shift mode: $SHIFT_MODE"
echo "$SHIFT_MODE" > "$SHIFT_MODE_FILE"

echo "Set battery mode: $BATTERY_MODE"
echo "$BATTERY_MODE" > "$BATTERY_MODE_FILE"
